### ISSUE TITLE
Examples missing body.disposition = render

### ISSUE THREAD

**Issue by coopdanger** [ietf-wg-mimi/draft-ietf-mimi-content#1]
Some of the examples are missing body.disposition = render, including 5.1, 5.2, 5.5.

**Comment by rohan-wire** [comment]
Addressed in [this commit](https://github.com/ietf-wg-mimi/draft-ietf-mimi-content/commit/277d2ad19185b0ea3359f68e35e72d765f94c895)

Thanks,
-rohan
