### ISSUE TITLE
For CBOR encoding decide if we want to tag URIs

### ISSUE THREAD

**Issue by rohanmahy** [ietf-wg-mimi/draft-ietf-mimi-content#12]

**Comment by rohanmahy** [comment]
Nobody has made any objection to tagging. It's only one octet per URI. Will close in 2 weeks unless there is an objection

**Comment by turt2live** [comment]
Can we get more information or an example of what this means?

**Comment by rohanmahy** [comment]
CBOR Web Tokens use URLs for the Issuer and Audience. The spec says specifically NOT to include a tag because the semantics of those fields clearly indicates the contents are a URL.

Conclusion. Don't add a URL tag to fields that are always a URL.

**Comment by rohanmahy** [comment]
Fixed
