### ISSUE TITLE
Decide if we use CBOR or TLS Presentation Language

### ISSUE THREAD

**Issue by rohanmahy** [ietf-wg-mimi/draft-ietf-mimi-content#14]

**Comment by tgeoghegan** [comment]
We discussed this at a [recent MIMI interim](https://datatracker.ietf.org/doc/minutes-interim-2024-mimi-03-202405081600/) and the held a [consensus call on the mailing list](https://mailarchive.ietf.org/arch/msg/mimi/L6CEupXf74lJ5_KuUoq6ipl-eik/). The conclusion is that we will be using CBOR. Let's repurpose this issue to track making that change to draft-ietf-mimi-content.

**Comment by rohanmahy** [comment]
CBOR version is being updated in PR #16. Closing.
