### ISSUE TITLE
Do we need a stronger hash for In reply to? for External content hash? for the message ID?

### ISSUE THREAD

**Issue by rohanmahy** [ietf-wg-mimi/draft-ietf-mimi-content#15]
CNSA 2.0 and other security guidelines no longer [recommend](https://media.defense.gov/2022/Sep/07/2003071834/-1/-1/0/CSA_CNSA_2.0_ALGORITHMS_.PDF) SHA-256.

## In Reply To

Should we make the default hash SHA-384 instead of SHA-256?

## External content

Should we make the default hash SHA-384 instead of SHA-256?

## Message ID

Currently the Message ID is the SHA-256 of the ciphertext of the message.The goal was to have a fixed length field

Options:
- Keep it SHA-256
- Make is the first 32 octets of the SHA-384 hash
- Make it the entire SHA-384 hash
- Make it a variable length so it can grow (but need to add down negotiation prevention)

**Comment by turt2live** [comment]
I wasn't at the interim (sorry), but +1 to sticking with sha256 until there's a good argument otherwise.

**Comment by rohanmahy** [comment]
Strong consensus to keeping SHA256. Marking as closed.
