### ISSUE TITLE
Support relative expiration times

### ISSUE THREAD

**Issue by rohanmahy** [ietf-wg-mimi/draft-ietf-mimi-content#22]
The current syntax allows expiration of messages at absolute times. However, self-deleting messages are more frequently implemented as an amount of time after the message is rendered to the user. It would be relatively straightforward to allow any message to use either an absolute or a relative expiration time.

**Comment by tgeoghegan** [comment]
POR is to support both absolute and relative expiration dates in the next draft.

**Comment by rohanmahy** [comment]
Fixed. See also new issue #39 about expiration extensibility.
