### ISSUE TITLE
Allow users (ex: moderators/administrators) other than the sender to edit/delete messages?

### ISSUE THREAD

**Issue by rohanmahy** [ietf-wg-mimi/draft-ietf-mimi-content#24]
timo brought up that moderators or administrators may want/need to ability to delete a message sent by another user, or even edit it. As long as we have policy knobs to prevent the abuse of such a feature, this seems reasonable.

**Comment by tgeoghegan** [comment]
@raphaelrobert: there should also be guidance on how these kinds of edits/deletes are presented to the user.

**Comment by rohanmahy** [comment]
Rohan to change the document to specify how authorization of edits/deletes should work. Mention UI issues

**Comment by rohanmahy** [comment]
Fixed. Policy Knob tracked in MIMI room policy issue [#1](https://github.com/ietf-wg-mimi/mimi-room-policy/issues/1)
