### ISSUE TITLE
manipulating topicId post facto

### ISSUE THREAD

**Issue by rohanmahy** [ietf-wg-mimi/draft-ietf-mimi-content#25]
From timo:

**Example 1**
1. Alice and Bob are regular users in a game development room.
2. Alice wants to throw an idea into the room, but does not think it's worth a new topic: "What about dragons?"
3. Bob has a lot of thoughts on the idea and wants to discuss it in detail.

He should be able to send a reply to Alice's message containing a new topicId.

**Example 2**
Here is another example for moderators moving messages to a different topic:

1. Alice is moderator in a causal room with 100 users, Bob is a regular user.
2. Alice created a "memes" topic where funny pictures can be shared without interrupting the discussion in the main room.
3. Bob is not aware of the topic and simply sends these pictures into the main room.

Alice should be allowed to send edits to the messages to move them into the "memes" topic.
Note: Depending on the room policy, moderators may be allowed to move messages to a topic, but not edit the content of the message

**Comment by mar-v-in** [comment]
An alternative to allowing others to add a `topic_id` to existing messages would be to have an implicit nameless `topic_id` based on the message's `message_id`.

This would mean that every message has a `topic_id`, for one of the following reason:
- First message in a thread with explicit named `topic_id` (like in Zulip)
- Out-of-thread message = first message in a thread with implicit nameless `topic_id`.
- Follow-up message in a thread explicitly using the `topic_id` of the first message in the thread.

**Comment by tgeoghegan** [comment]
Distinct from #24, but similar policy considerations apply.

**Comment by rohanmahy** [comment]
Fixed. Policy Knob tracked in MIMI room policy issue [#1](https://github.com/ietf-wg-mimi/mimi-room-policy/issues/1)
