### ISSUE TITLE
Get rid of partIndex or make it optional

### ISSUE THREAD

**Issue by mar-v-in** [ietf-wg-mimi/draft-ietf-mimi-content#31]
Currently, it is strictly required to assign a `partIndex` to every part in depth-first counting. This makes it superfluous to transfer it as the `partIndex` can always be derived on the recipient side (and the recipient is also expected to verify the `partIndex` and discard messages with invalid assignments).

Additionally, the `partIndex` makes things rather complex on the sender side as the index of a specific part is only known after the final message structure is constructed. Usually the message payload is available first (e.g. the user writes a message in the chat client and attaches files or adds them inline) and the structure is derived thereof. The current design requires the client to first build the part structure and then adjust the user-created HTML to correctly reference the respective part.

I thus suggest one of the following:
- Get rid of the explicit `partIndex` in the transferred data and expect the recipient to assign `partIndex` when receiving the message
- Make `partIndex` optional and allow it to be non-continuous. Sending clients would only put `partIndex` to parts that they seem sensible to reference in the future.
- A combination of the two: Get rid of explicit `partIndex` but allow putting an optional explicit textual content-id. Allow senders/recipients to either reference the part by the implicit `partIndex` or the explicit content-id. This makes it possible to reference every part of a generates message but solves the issues with complexity during message generation.

**Comment by rohanmahy** [comment]
Requires solution to #30

**Comment by rohanmahy** [comment]
Take to the mailing list after addressing #30

**Comment by rohanmahy** [comment]
Fixed
