### ISSUE TITLE
While using c++ syntax, should use std::optional

### ISSUE THREAD

**Issue by alvestrand** [ietf-wg-mimi/draft-ietf-mimi-content#8]
A number of fields in the abstract syntax have descriptions with words like "does not expire if zero", "if the topic field is empty, there is no such grouping".

The description will be clearer, and easier to translate into a new concrete syntax when we decide upon one, if we use std::optional<type> instead of "type with comment saying when it's empty".

**Comment by rohanmahy** [comment]
Thanks Harald,
As of draft -03 we are no longer using C++ syntax. We have a TLS PL and CBOR syntax and need to pick one.

Closing.
